apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: example-app
data:
  NODE_ENV: "development"
  PORT: "3000"
  DB_HOST: <DB_HOST>
  DB_PORT: "3306"
  DB_NAME: <DB_NAME>
  TYPEORM_CONNECTION: "mysql"
  TYPEORM_HOST: <DB_HOST>
  TYPEORM_PORT: "3306"
  TYPEORM_DATABASE: <DB_NAME>
  TYPEORM_SYNCHRONIZE: "false"
  TYPEORM_LOGGING: "true"
  TYPEORM_ENTITIES: "dist/entity/**/*.js"
  TYPEORM_MIGRATIONS: "dist/migration/**/*.js"
  TYPEORM_SUBSCRIBERS: "dist/subscriber/**/*.js"
  TYPEORM_MIGRATIONS_RUN: "true"