apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: example-app
type: Opaque
stringData:
  DB_USER: <DB_USERNAME>
  DB_PASSWORD: <DB_PASSWORD>
  TYPEORM_USERNAME: <DB_USERNAME>
  TYPEORM_PASSWORD: <DB_PASSWORD>